Validate is partitioned
databrickslabs/ucx pull request #1044
Opened 2024-03-11 21:55 UTC by dleiva04

#  Changes

### Linked issues

Resolves #871 

Related PR:
- https://github.com/databrickslabs/ucx/pull/985

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [X] modified existing table: `ucx.tables`

### Tests

- [X] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

![image](https://github.com/databrickslabs/ucx/assets/23179165/980bd9be-fc36-405f-b21b-186629097a92)
![image](https://github.com/databrickslabs/ucx/assets/23179165/7e81cd04-a5eb-4944-a43e-d0a89d794bca)

2024-03-11 22:04 UTC, dleiva04 commented on src/databricks/labs/ucx/hive_metastore/tables.scala
Reformat the file for better reading, if this is wrong I can change it back

2024-03-14 18:47 UTC, nfx requested changes
please rename the upgrade script to start with `v0.17.0_...` and rebase on the latest `main`. Also create the PR directly on this repo instead of your fork. you can do that by changing the `origin` in `.git/config` file

2024-03-22 11:27 UTC, nfx commented
@dleiva04 please rebase/update with the latest released version

2024-03-26 20:33 UTC, closed without merging

2024-03-26 20:33 UTC, dleiva04 commented
Going to create directly into this repo