Add `migrate-tables` workflow
databrickslabs/ucx pull request #1045
Opened 2024-03-12 06:56 UTC by qziyuan

## Changes
Add `migrate-tables` workflow. This PR includes the workflow only described in milestone 1 in #1035 
`table_migration_progress` table is out of scope in this PR.

### Linked issues

Relates #333 #670 

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [x] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [x] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-03-12 14:38 UTC, qziyuan commented on src/databricks/labs/ucx/install.py
> +        if "migration_clone" in names:
We have two types migration: 

1. In place migrate that just migrate the metadata to UC, like SYNC command, this just need a a small cluster.
2. migration that need to do data copy, like deep clone and CTAS for dbfs root tables. This we need larger cluster.

2024-03-12 23:04 UTC, qziyuan commented on src/databricks/labs/ucx/install.py
> +        if "migration_clone" in names:
let's use just one cluster, since we default auto scale with one worker.

2024-03-13 07:08 UTC, qziyuan commented on src/databricks/labs/ucx/runtime.py
> +def migrate_views(cfg: WorkspaceConfig, ws: WorkspaceClient, sql_backend: SqlBackend, installation: Installation):
fixed

2024-03-13 07:09 UTC, qziyuan commented on src/databricks/labs/ucx/install.py
> +                            max_workers=10,
refactored, please review

2024-03-13 07:09 UTC, qziyuan commented on src/databricks/labs/ucx/install.py
> +                        # spark_conf={"spark.sql.sources.parallelPartitionDiscovery.parallelism": "1000"},
refactored, please review

2024-03-13 07:09 UTC, qziyuan commented on src/databricks/labs/ucx/framework/tasks.py
> +        if current_task.workflow == "migrate-tables":
fixed

2024-03-13 07:10 UTC, qziyuan commented on tests/unit/framework/test_tasks.py
> +    mock_api_request = create_autospec(PreparedRequest)
I don't get this. Could you elaborate more?

2024-03-13 08:51 UTC, nfx requested changes
How can we make it without a breaking change?

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/framework/tasks.py
> +    fn: AssessmentFunctions | MigrationFunctions
Revert this change.

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/install.py
> +def load_cluster_specs() -> dict[str, ClusterSpec]:
Don't load something from a yaml file if it can be defined as 5 lines of python code. Revert

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/install.py
> +        cluster_specs = load_cluster_specs()
Don't load from yaml, define it in code

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/install.py
> +        cluster_specs = self._config.cluster_specs
No, this gets too fragile. Installer is the critical component and this introduces severe risk of breakage. Revert.

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/runtime.py
> +def crawl_grants(cfg: WorkspaceConfig, _: WorkspaceClient, sql_backend: SqlBackend, _installation: Installation):
```suggestion
def crawl_grants(cfg: WorkspaceConfig, _: WorkspaceClient, sql_backend: SqlBackend, install: Installation):
```

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/upgrades/v0.16.0_added_cluster_spec.py
> +    for _, cluster_spec in cluster_specs.items():
This is too risky. How can we do it without a breaking change?

2024-03-13 08:51 UTC, nfx commented on tests/unit/framework/test_tasks.py
> +    mock_api_request = create_autospec(PreparedRequest)
ws.get_workspace_id.return_value = 123

2024-03-13 08:51 UTC, nfx commented on src/databricks/labs/ucx/config.py
> +    cluster_specs: dict[str, ClusterSpec] | None = None
This is a breaking change. How can we do without it?

2024-03-14 02:29 UTC, closed without merging

2024-03-14 02:29 UTC, qziyuan commented
Close this draft PR. Please review the new PR #1051

2024-03-14 02:39 UTC, nfx commented on src/databricks/labs/ucx/install.py
> +                            max_workers=10,
Can you put 10 as a variable in config?