Add prompts for table migration job cluster configuration in WorkflowInstallation
databrickslabs/ucx pull request #1195
Opened 2024-04-01 02:21 UTC by qziyuan

## Changes

#1055 removed the prompts for configuring the auto-scale and parallelism for table migration job cluster.
This PR add the prompts back in the WorkflowInstallation, and update the WorkspaceConfig to persist the config values.

### Linked issues

Resolves #..

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [x] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-04-01 06:35 UTC, qziyuan commented
> ❌ 136/138 passed, 1 flaky, 2 failed, 20 skipped, 1h37m32s total
> 
> ❌ test_compare_remote_local_install_versions: Failed: DID NOT RAISE (1m39.395s)
> ❌ test_check_inventory_database_exists: Failed: DID NOT RAISE (1m47.155s)
> Flaky tests:
> 
> * 🤪 test_group_name_change[matching] (34.589s)
> 
> Running from [acceptance #1927](https://github.com/databrickslabs/ucx/actions/runs/8502907957/job/23288593781)

Need #1196 to be merged.

2024-04-01 07:54 UTC, nfx requested changes

2024-04-01 16:22 UTC, qziyuan commented on src/databricks/labs/ucx/installer/workflows.py
> +        parallelism = self._prompts.question(
The prompts are being processed only in this `configure` function, which should be called only once when a fresh installation is being created. In the case of installing on the account level on 600 workspaces, this `configure` function should be called where the configuration are being created at first time. And then the configuration can be replicated 600 times.
@FastLee Please review this code and see if it's what you were asking. Serge is making a good point here, I agree we should handle all prompts in one place. Although it does not fully separate out workflow from the workspace install, but the structure is more clear: we have all prompts processed and configuration initiated first, then workflow installation and workspace installation will run based on the configuration.

2024-04-01 18:39 UTC, nfx requested changes

2024-04-01 18:39 UTC, nfx commented on src/databricks/labs/ucx/installer/workflows.py
> +        parallelism = self._prompts.question(
@qziyuan the only place in the installer that is allowed to do configuration-requesting prompts is this method and it's downstreams. Table migration configuration has to happen there and being reflected on `WorkspaceConfig`.

https://github.com/databrickslabs/ucx/blob/601b54daa76493ddeb2e0b9c5e0cd3f3bbb13351/src/databricks/labs/ucx/install.py#L223-L266

the only remaining place where we depend on prompts in this class is configuring cluster overrides when DBFS is not writable. This confused you and caused you to **add a method in a wrong place** for a right reason.

<img width="875" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/09cad172-c9bf-41fc-b8b1-98170f718006">

In a separate PR, remove the `Prompts` dependency from `WorkflowsInstallation`. It doesn't belong there even in the medium term.

2024-04-02 00:08 UTC, nfx approved these changes
Lgtm

2024-04-02 00:09 UTC, merged