[WIP] add command for migrating views
databrickslabs/ucx pull request #1232
Opened 2024-04-03 10:17 UTC by ericvergnaud

## Changes
add a command for migrating views
factorize code

### Linked issues
Resolves https://github.com/databrickslabs/ucx/issues/1172

### Functionality 

- [ ] added relevant user documentation
- [x] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests
- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

Missing integration tests
Depends on #1177

2024-04-04 18:32 UTC, qziyuan requested changes
Hi @ericvergnaud could you take a look at and double check this issue #1273? I think the old `_migrate_view_table` function is creating UC view with old HMS dependencies.

2024-04-05 07:21 UTC, ericvergnaud commented
@qziyuan sure - I've asked @nfx how I should prioritize

2024-04-05 09:08 UTC, JCZuurmond requested changes
Your changes LGTM. However, there was a problem already that should be addressed first, see the comment above.

2024-04-05 09:08 UTC, JCZuurmond commented on src/databricks/labs/ucx/runtime.py
> -        azure_client = AzureAPIClient(
See message in Slack from @nfx about these calls only existing from the cli not within a job

2024-04-11 12:11 UTC, nfx commented
closing in favor of https://github.com/databrickslabs/ucx/pull/1325

2024-04-11 12:12 UTC, closed without merging