Added support for one level notation for query transformer.
databrickslabs/ucx pull request #1288
Opened 2024-04-05 17:55 UTC by FastLee

Related to #331

2024-04-06 09:31 UTC, nfx requested changes

2024-04-06 09:31 UTC, nfx commented on src/databricks/labs/ucx/source_code/queries.py
> +    def apply(self, code: str, *, use_schema: str = "") -> str:
You are not allowed to change the Fixer interface.

Why do you need a parameter here? Please explain. See also:

- https://github.com/databrickslabs/ucx/issues/1215

2024-04-08 10:53 UTC, ganeshgirase reviewed
method lint and apply have almost around 8 - 10 lines common which is to get statement , validate statement, tables and their catalogs. This can be generalised into common code and we can achieve lazy evaluation here.

2024-04-08 19:22 UTC, nfx commented
as discussed, this is not the right way to implement it

2024-04-08 19:22 UTC, closed without merging