Show tables migration status in estimates dashboard
databrickslabs/ucx pull request #1507
Opened 2024-04-23 15:27 UTC by JCZuurmond

## Changes
Extend "tables to migrate" query to include table migration status

### Linked issues
Resolves #323

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-04-23 15:30 UTC, JCZuurmond reviewed
Some checks on the query

2024-04-23 15:30 UTC, JCZuurmond commented on src/databricks/labs/ucx/queries/assessment/estimates/02_2_uc_data_modeling.sql
> +-- viz type=table, name=Tables to migrate, search_by=catalog,database,name,upgraded_status columns=catalog,database,name,object_type,table_format,location,view_text,upgraded_to,storage_properties
Need to test the search by on multiple columns

2024-04-25 07:17 UTC, nfx approved these changes
Lgtm

2024-04-29 09:18 UTC, JCZuurmond commented
Screenshots

<img width="1920" alt="Screenshot 2024-04-29 at 11 16 27" src="https://github.com/databrickslabs/ucx/assets/5946784/f71f71a9-0fe1-438b-82f1-0aaea212b3b7">
<img width="1920" alt="Screenshot 2024-04-29 at 11 17 24" src="https://github.com/databrickslabs/ucx/assets/5946784/987f2e62-870a-4472-afae-6ac53d57c6ad">

2024-04-30 12:46 UTC, nfx requested changes

2024-04-30 12:46 UTC, nfx commented on src/databricks/labs/ucx/queries/assessment/estimates/02_2_uc_data_modeling.sql
> +SELECT
could you add/modify this in the `main` dashboard instead of `estimates`.

2024-04-30 12:46 UTC, nfx commented on src/databricks/labs/ucx/queries/assessment/estimates/02_2_uc_data_modeling.sql
> +      ELSE 'Stayed in place'
```suggestion
      WHEN migration_status.dst_table IS NOT NULL THEN 'Yes'
      ELSE 'No'
```

2024-04-30 12:46 UTC, nfx commented on src/databricks/labs/ucx/queries/assessment/estimates/02_2_uc_data_modeling.sql
> +    $inventory.migration_status AS migration_status
please attach a screenshot after running the `migrate-tables` workflow. Add (or use) an existing integration test case, that migrates external table and a view.

https://github.com/databrickslabs/ucx/blob/00d2e6e80dfd19c3b83e6557a036093d0b42bb3b/src/databricks/labs/ucx/hive_metastore/workflows.py#L7-L37

here's the test:
https://github.com/databrickslabs/ucx/blob/00d2e6e80dfd19c3b83e6557a036093d0b42bb3b/tests/integration/test_installation.py#L349-L392

perhaps you'd need to do something along the lines of:

```
@job_task(
        job_cluster="table_migration",
        depends_on=[migrate_external_tables_sync, migrate_dbfs_root_delta_tables, migrate_views],
    )
    def refresh_migration_status(self, ctx: RuntimeContext):
        """Refreshes migration status table"""
        ...
```

and you'd have to modify the `MigrateHiveSerdeTablesInPlace` workflow the same way

2024-04-30 19:39 UTC, JCZuurmond commented
![Screenshot 2024-04-30 at 21 37 19](https://github.com/databrickslabs/ucx/assets/5946784/fefba613-90a3-4000-9010-795789f4c203)

- [ ] Add screenshots after running all migration workflows

2024-04-30 19:42 UTC, JCZuurmond reviewed
The documentation can use some extra attention. The changes add a separate dashboard for the migration status ☝️

2024-05-01 07:56 UTC, JCZuurmond commented
Screen shot after running all migration jobs

<img width="1740" alt="Screenshot 2024-05-01 at 09 54 35" src="https://github.com/databrickslabs/ucx/assets/5946784/0fd24191-ec0f-417b-9dec-147357ce24df">

2024-05-01 07:59 UTC, JCZuurmond commented
@nfx : Implemented your feedback, please have another look

2024-05-01 17:53 UTC, nfx approved these changes
lgtm

2024-05-01 17:53 UTC, merged