Add linter to check for RDD use and JVM access
databrickslabs/ucx pull request #1606
Opened 2024-05-02 12:31 UTC by vsevolodstep-db

## Changes

### Linked issues
Resolves https://github.com/databrickslabs/ucx/issues/1603, https://github.com/databrickslabs/ucx/issues/1604

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ x ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-05-02 19:09 UTC, nfx requested changes

2024-05-03 13:39 UTC, vsevolodstep-db commented on src/databricks/labs/ucx/source_code/spark_connect.py
> +        "newAPIHadoopFile",
Is that a problem though? The error messages will be different, can't we have them both?

2024-05-03 15:22 UTC, nfx approved these changes
Lgtm

2024-05-06 19:58 UTC, nfx approved these changes
Lgtm

2024-05-06 19:58 UTC, merged