WIP: Add initial interface for Data comparison framework
databrickslabs/ucx pull request #1695
Opened 2024-05-15 06:00 UTC by bishwajit-db

Add initial interface for Data comparison framework

2024-05-15 06:24 UTC, sundarshankar89 commented
@nkvuong Initial WIP PR.

2024-05-15 10:30 UTC, bishwajit-db commented on pyproject.toml
> +    "pyspark>=3.5.0",
Removed

2024-05-15 10:31 UTC, bishwajit-db commented on src/databricks/labs/ucx/recon/_schema_comparator.py
> +    def compare_schema(self, source: DataFrame, target: DataFrame) -> SchemaComparisonResult:
Done

2024-05-15 10:49 UTC, bishwajit-db commented on src/databricks/labs/ucx/recon/_data_profiler.py
> +    def profile_data(self, source: DataFrame) -> DataProfilingResult:
Done

2024-05-15 10:58 UTC, sundarshankar89 requested changes

2024-05-15 10:58 UTC, sundarshankar89 commented on src/databricks/labs/ucx/recon/_base.py
> +class TableMetadataRetriever(ABC):
do you really want this to be separate, not as a property of the profiler?

2024-05-15 10:58 UTC, sundarshankar89 commented on src/databricks/labs/ucx/recon/_data_profiler.py
> +    def profile_data(self, source: TableDescriptor) -> DataProfilingResult:
nit:
```suggestion
    def profile_data(self, entity: TableDescriptor) -> DataProfilingResult:
```

2024-05-15 10:58 UTC, sundarshankar89 commented on src/databricks/labs/ucx/recon/_data_profiler.py
> +    def _get_table_row_count(self, source: TableDescriptor) -> int:
nit:
```suggestion
    def _get_table_row_count(self, entity: TableDescriptor) -> int:
```

2024-05-15 10:58 UTC, sundarshankar89 commented on src/databricks/labs/ucx/recon/_metadata_retriever.py
> +def _prepare_metadata_query(source: TableDescriptor) -> str:
nit: 
```suggestion
def _prepare_metadata_query(entity: TableDescriptor) -> str:
```

2024-05-15 10:58 UTC, sundarshankar89 commented on src/databricks/labs/ucx/recon/_metadata_retriever.py
> +    def get_metadata(self, source: TableDescriptor) -> TableMetadata:
nit:
```suggestion
    def get_metadata(self, entity: TableDescriptor) -> TableMetadata:
```

2024-05-15 11:51 UTC, nkvuong requested changes
don't forget to run `make fmt`

also since this decreases code coverage, it won't be auto-merged :)

2024-05-15 11:51 UTC, nkvuong commented on src/databricks/labs/ucx/recon/_base.py
> +class TableDescriptor:
we already have a Table dataclass that you can reuse
https://github.com/databrickslabs/ucx/blob/953c4837614b355d03bac9c0f201ca2a39e11a14/src/databricks/labs/ucx/hive_metastore/tables.py#L50-L54

2024-05-15 11:51 UTC, nkvuong commented on src/databricks/labs/ucx/recon/_base.py
> +class SchemaComparisonEntry:
you could reuse/extend https://github.com/databrickslabs/ucx/blob/953c4837614b355d03bac9c0f201ca2a39e11a14/src/databricks/labs/ucx/hive_metastore/mapping.py#L23-L29
or 
https://github.com/databrickslabs/ucx/blob/953c4837614b355d03bac9c0f201ca2a39e11a14/src/databricks/labs/ucx/hive_metastore/mapping.py#L63-L65

2024-05-15 11:51 UTC, nkvuong commented on src/databricks/labs/ucx/recon/_schema_comparator.py
> +def _compare_col_metadata(source_col: ColumnMetadata, target_col: ColumnMetadata) -> bool:
should define a `__eq__` method for `ColumnMetadata` class instead

2024-05-17 13:19 UTC, nkvuong approved these changes

2024-05-20 04:09 UTC, sundarshankar89 approved these changes
LGTM

2024-05-20 04:12 UTC, merged