Add pip installer
databrickslabs/ucx pull request #1697
Opened 2024-05-15 07:37 UTC by JCZuurmond

## Changes
Add a pip installer. 

@ericvergnaud and I concluded to separate the installing of libraries from register/linting them. An installer makes a library available to the path look up by i) installing the library and ii) augmenting the path lookup.

### Linked issues
Resolves #1642
Follow up on #1694 

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-05-15 09:08 UTC, nfx submitted a review, later dismissed
Why do we need to introduce new concepts and increase levels of indirection? Please provide trade-off analysis matrix with pros and cons of each approach.

2024-05-15 13:37 UTC, JCZuurmond commented
> Why do we need to introduce new concepts and increase levels of indirection? Please provide trade-off analysis matrix with pros and cons of each approach.

Added motivation to the first PR comment

2024-05-15 15:33 UTC, ericvergnaud requested changes

2024-05-15 15:33 UTC, ericvergnaud commented on src/databricks/labs/ucx/contexts/application.py
> +        import_resolvers = [self.pip_resolver, self.file_resolver, self.whitelist_resolver]
The pip resolver is NOT an import resolver. You need to add a _library_resolver member in DependencyResolver with type BaseLibraryResolver

2024-05-15 15:33 UTC, ericvergnaud commented on src/databricks/labs/ucx/contexts/application.py
> +        import_resolvers = [self.pip_resolver, self.file_resolver, self.whitelist_resolver]
And PipResolver should derive from BaseLibraryResolver

2024-05-15 15:33 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/graph.py
> +    def resolve_library_pip(self, path_lookup: PathLookup, name: str) -> MaybeDependency:
No, this goes against the rationale provided in the PR: introduces confusion and complexity

2024-05-15 15:33 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/graph.py
> +    def resolve_library_pip(self, path_lookup: PathLookup, name: str) -> MaybeDependency:
no, see above

2024-05-15 15:33 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/site_packages.py
> +class PipResolver(BaseImportResolver):
no, you need to derive from BaseLibraryResolver

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_graph.py
> +def test_dependency_graph_register_library(mock_path_lookup):
`registers` not `register`

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +def test_workflow_task_container_build_dependency_graph_not_yet_implemented(mock_path_lookup, graph):
"...reports_not_yet_implemented_problem"

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +def test_workflow_task_container_build_dependency_graph_empty_task(mock_path_lookup, graph):
`builds` not `build`

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +    """No dependency problems with empty task"""
remove

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +    """Receive not yet implemented problems"""
remove

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +def test_workflow_task_container_build_dependency_graph_pytest_pypi_library(mock_path_lookup, graph):
` builds`  not `build`

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +    """Install pytest PyPi library"""
remove

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +    """Install unknown PyPi library"""
remove

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +def test_workflow_task_container_build_dependency_graph_unknown_pypi_library(mock_path_lookup, graph):
`builds` not `build`

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_site_packages.py
> +def test_pip_resolver_library(mock_path_lookup):
rename to test_pip_resolver_resolves_library

2024-05-15 15:33 UTC, ericvergnaud commented on tests/unit/source_code/test_site_packages.py
> +def test_pip_resolver_unknown_library(mock_path_lookup):
test_pip_resolver_does_not_resolve_unknown_library

2024-05-15 15:41 UTC, ericvergnaud requested changes

2024-05-15 15:41 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/graph.py
> +        maybe = self._resolver.resolve_library(self.path_lookup, library)
Don't remove the TODOs, there's still work to be done here, just not as part of this PR

2024-05-15 15:52 UTC, ericvergnaud commented on tests/unit/source_code/test_jobs.py
> +def test_workflow_task_container_build_dependency_graph_unknown_pypi_library(mock_path_lookup, graph):
is it not a duplicate of test_pip_resolver_unknown_library ?

2024-05-16 08:47 UTC, ericvergnaud approved these changes

2024-05-16 09:15 UTC, merged