WhitelistResolver must be invoked before other import resolvers
databrickslabs/ucx pull request #1709
Opened 2024-05-17 09:31 UTC by ericvergnaud

## Changes
Ensure that WhitelistResolver, if present, is always imported first

### Linked issues
Resolves #1707 

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests
- [ ] manually tested
- [x] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-05-17 14:28 UTC, pritishpai approved these changes
LGTM!

2024-05-21 06:54 UTC, JCZuurmond requested changes
Could we revert the list? Now "first" is the last resolver in the list, which reads confusing

2024-05-21 13:34 UTC, nfx requested changes
instead of making a hack, make the structure easy to work with.

```mermaid
graph TD

PathLookup -->|inject into| resolve_import
DependencyResolver -->|call|resolve_import
resolve_import -.->|method of| ImportResolver
Whitelist -->|inject into constructor| ImportResolver
FileLoader --> |inject into constructor| ImportResolver
```

2024-05-21 13:34 UTC, nfx commented on src/databricks/labs/ucx/source_code/graph.py
> +        # check that WhiteListResolver comes first when resolving import
we currently have:
<img width="855" alt="image" src="https://github.com/databrickslabs/ucx/assets/259697/0a516780-e6d1-44ce-bb86-1a59c42733be">

```mermaid
graph TD

PathLookup -->|inject into| resolve_import
DependencyResolver -->|call|resolve_import

resolve_import -.->|method of| BaseImportResolver
BaseImportResolver -.->|subclass| LocalFileResolver
BaseImportResolver -.->|subclass| WhitelistResolver
BaseImportResolver -.->|subclass| StubImportResolver
LocalFileResolver -.->|next| WhitelistResolver
WhitelistResolver -.->|next| StubImportResolver

Whitelist --> WhitelistResolver
FileLoader --> LocalFileResolver
```
this is hard to work with and requires code like this to fix flaw on the higher level.

# Simplify

```mermaid
graph TD

PathLookup -->|inject into| resolve_import
DependencyResolver -->|call|resolve_import
resolve_import -.->|method of| ImportResolver
Whitelist -->|inject into constructor| ImportResolver
FileLoader --> |inject into constructor| ImportResolver
```

2024-05-22 16:36 UTC, ericvergnaud commented
superseded by #1746

2024-05-22 16:36 UTC, closed without merging