Support for s3a/ s3n protocols when using mount point
databrickslabs/ucx pull request #1723
Opened 2024-05-20 14:40 UTC by wesleyforti

…port for protocols like s3a and s3n

## Changes
![image](https://github.com/databrickslabs/ucx/assets/12300863/9a44e04a-87c7-4927-bbfd-a3e22dcb1623)

### Linked issues
https://github.com/databrickslabs/ucx/issues/1722

Resolves #
External tables that uses s3a and s3n as protocolos when using mount points

### Functionality 

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [X] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests
rerun validate-external-location command and check both log files and generated terraform tf file
- [x] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-05-20 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/databrickslabs/ucx?pullRequest=1723) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/databrickslabs/ucx?pullRequest=1723) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/databrickslabs/ucx?pullRequest=1723) it.</sub>

2024-05-20 15:44 UTC, nkvuong commented
@wesleyforti could you add/modify a unit test for this?

2024-05-21 13:56 UTC, nfx requested changes

2024-05-21 13:56 UTC, nfx commented on src/databricks/labs/ucx/hive_metastore/locations.py
> +            if loc.location.startswith(("s3://", "s3a://", "s3n://")):
```suggestion
            for prefix in ("s3://", "s3a://", "s3n://"):
                prefix_len = len(prefix)
```
please make it more readable and add a unit test.

2024-05-24 12:38 UTC, nkvuong commented
Superseded by #1765

2024-05-24 12:38 UTC, closed without merging