Remove test jobs created in CI after twelve hours
databrickslabs/ucx pull request #1861
Opened 2024-06-07 13:57 UTC by JCZuurmond

## Changes
Remove test jobs created in CI after twelve hours

### Linked issues
Helps with investigating #1857

### Tests

- [ ] manually tested

2024-06-07 15:25 UTC, JCZuurmond commented on src/databricks/labs/ucx/installer/workflows.py
> +        timeout = TEST_CI_JOBS_PURGE_TIMEOUT if self._is_ci() else TEST_JOBS_PURGE_TIMEOUT
Change this to only increase it to twelve hours for nightly runs

2024-06-07 15:49 UTC, nfx requested changes

2024-06-07 15:49 UTC, nfx commented on src/databricks/labs/ucx/installer/workflows.py
> +        ci_env = os.getenv("CI")
use `TEST_NIGHTLY` and rename the accessor

2024-06-07 15:49 UTC, nfx commented on src/databricks/labs/ucx/installer/workflows.py
> +TEST_CI_JOBS_PURGE_TIMEOUT = timedelta(hours=12)  # Buffer for debugging nightly integration test runs
12 hours is too much, let's limit at 3 hours.

2024-06-10 15:26 UTC, nfx approved these changes

2024-06-10 15:26 UTC, merged