Expose code linters as a LSP plugin
databrickslabs/ucx pull request #1921
Opened 2024-06-19 14:52 UTC by vsevolodstep-db

## Changes
Add a PyLSP plugin entrypoint for UCX code linters. When a user has `python-lsp-server` installed, UCX will automatically register an LSP plugin on installation. 

### Tests

- [x] manually tested
- [x] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-06-19 16:39 UTC, nfx requested changes

2024-06-19 16:39 UTC, nfx commented on src/databricks/labs/ucx/source_code/lsp_plugin.py
> +languages = LinterContext(index=None, session_state=None)
Init linter context for every document, because it's stateful

2024-06-24 14:09 UTC, JCZuurmond commented on src/databricks/labs/ucx/source_code/linters/context.py
> +            python_linters.append(SparkSql(from_table, index, session_state))
This is now the last linter, where it was the first before

2024-06-24 14:10 UTC, JCZuurmond commented on src/databricks/labs/ucx/source_code/linters/context.py
> +    def __init__(self, index: MigrationIndex | None, session_state: CurrentSessionState | None = None):
```suggestion
    def __init__(self, index: MigrationIndex | None, session_state: CurrentSessionState | None = None):
```
```suggestion
    def __init__(self, index: MigrationIndex | None = None, session_state: CurrentSessionState | None = None):
```
```suggestion
    def __init__(self, index: MigrationIndex | None, session_state: CurrentSessionState | None = None):
```

2024-06-26 11:17 UTC, vsevolodstep-db commented
Not sure what can I do about no-check check there. LSP plugin system requires `pylsp_lint` hook to have two arguments with specified names (`workspace` and `document`)

2024-07-02 18:07 UTC, nfx approved these changes
lgtm

2024-07-02 18:07 UTC, nfx commented on tests/unit/source_code/test_lsp_plugin.py
> +    code = 'sc.emptyRDD()'
we may want to add one more test with 2-3 lines of code to make sure line offsets are working fine.

2024-07-02 18:07 UTC, merged