Tidy up whitespace
databrickslabs/ucx pull request #1923
Opened 2024-06-20 09:13 UTC by asnare

## Changes

This PR follows on from #1778 by cleaning up files that use tabs, have trailing whitespace, or are missing EOL at the end of files. By fixing these in one go other PRs become less noisy. (Sample files used in tests have been left alone and are not affected by this PR.)

2024-06-24 14:22 UTC, JCZuurmond requested changes
Is this the effect of changing a linter setting somewhere? The Changelog changes are a bit tricky, they will come. back

2024-06-25 08:28 UTC, asnare commented
> Is this the effect of changing a linter setting somewhere?

It's a side-effect of the editor settings in #1778. Historically we have quite a few files with trailing whitespace and missing the EOL at EOF. These aren't enforced by linting (which only covers python code), but with the new editor settings in place any time you modify a file trailing whitespace elsewhere in the file will be stripped. This was intended as a fix-them-all-for-now PR to avoid spurious updates on other PRs, particularly in Markdown.

> The Changelog changes are a bit tricky, they will come back

Agreed; I'm happy to drop those given that the file is generated.

2024-06-27 19:54 UTC, JCZuurmond approved these changes

2024-07-02 12:30 UTC, nfx commented on LICENSE
> +    Definitions.
please revert changes to this file

2024-07-05 07:34 UTC, nfx approved these changes
lgtm

2024-07-05 07:34 UTC, merged