whitelist bitsandbytes
databrickslabs/ucx pull request #2048
Opened 2024-07-03 10:50 UTC by ericvergnaud

## Changes
whitelist bitsandbytes

### Linked issues
Progresses #1901 

### Functionality 
None

### Tests
- [x] manually tested

2024-07-08 08:09 UTC, nfx requested changes

2024-07-08 08:09 UTC, nfx commented on src/databricks/labs/ucx/source_code/known-readme.txt
> +Known libraries that are not in known.json
remove this file

2024-07-08 08:52 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/known-readme.txt
> +Known libraries that are not in known.json
done

2024-07-09 07:16 UTC, nfx approved these changes
lgtm

2024-07-09 07:16 UTC, nfx commented
make CI pass

2024-07-09 10:13 UTC, ericvergnaud commented
> make CI pass

done

2024-07-09 18:01 UTC, merged