whitelist fasttext
databrickslabs/ucx pull request #2050
Opened 2024-07-03 10:54 UTC by ericvergnaud

## Changes
whitelist fasttext

### Linked issues
Progresses #1901 

### Functionality 
None

### Tests
- [x] manually tested

2024-07-08 08:10 UTC, nfx requested changes

2024-07-08 08:10 UTC, nfx commented on src/databricks/labs/ucx/source_code/known.json
> +    "fasttext.tests": [],
remove tests

2024-07-08 08:54 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/known.json
> +    "fasttext.tests": [],
done

2024-07-09 18:01 UTC, nfx approved these changes
lgtm

2024-07-09 18:01 UTC, merged