whitelist hail
databrickslabs/ucx pull request #2053
Opened 2024-07-03 11:01 UTC by ericvergnaud

## Changes
whitelist hail

### Linked issues
Progresses #1901 

### Functionality 
None

### Tests
- [x] manually tested

2024-07-08 08:12 UTC, nfx requested changes

2024-07-08 08:12 UTC, nfx commented on src/databricks/labs/ucx/source_code/known.json
> +        "message": "Deprecated file system path: /mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"
this is a false positive

2024-07-08 08:58 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/known.json
> +        "message": "Deprecated file system path: /mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"
fixed

2024-07-09 18:03 UTC, nfx approved these changes
lgtm

2024-07-09 18:03 UTC, merged