whitelist geoip2
databrickslabs/ucx pull request #2064
Opened 2024-07-03 11:42 UTC by ericvergnaud

## Changes
whitelist geoip2
Pull requests
19

2024-07-09 18:25 UTC, nfx requested changes

2024-07-09 18:25 UTC, nfx commented on src/databricks/labs/ucx/source_code/known-readme.txt
> +1) libraries with Python syntax that astroid cannot parse
revert this

2024-07-10 08:37 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/known-readme.txt
> +1) libraries with Python syntax that astroid cannot parse
done

2024-07-10 08:39 UTC, JCZuurmond approved these changes

2024-07-10 10:50 UTC, merged