Mock WheelsV2 in unit-tests to avoid lengthy wheel-building.
databrickslabs/ucx pull request #2281
Opened 2024-07-30 15:48 UTC by asnare

## Changes

This PR updates some of the unit-testing fixtures to mock `WheelsV2` where this is referenced instead of the real thing; this avoids lengthy wheel-building during unit tests.

(Wheel-building can easily exceed the 30s unit-testing deadline, especially on developer laptops with the solacc dataset present.)

2024-07-30 15:49 UTC, JCZuurmond requested changes
I expect a `assert_` to be required on the mock

2024-07-31 08:59 UTC, JCZuurmond approved these changes
Mock is oke as it is not within the scope of the test

2024-07-31 09:05 UTC, asnare commented
> I expect a `assert_` to be required on the mock

I didn't realise yesterday that this feedback was intended to address an expecting linting failure: pylint has checks for unused mocks. However these checks are don't (seem to?) apply when the mock is being created as part of the fixture.

2024-07-31 10:35 UTC, asnare commented
AFAICT tell the failing acceptance tests are not related to changes in this PR.

2024-07-31 18:20 UTC, merged