Update TODO about dashboard installation retry on `InternalError`
databrickslabs/ucx pull request #2338
Opened 2024-08-01 07:14 UTC by JCZuurmond

## Changes
Update TODO about dashboard installation retry on `InternalError` to be more descriptive and actionable.

### Linked issues
Resolves #2172
Resolves #2173
Resolves #2198

2024-08-01 08:24 UTC, ericvergnaud commented
lgtm

2024-08-01 08:25 UTC, ericvergnaud requested changes

2024-08-01 08:25 UTC, ericvergnaud commented on src/databricks/labs/ucx/install.py
> +    # why this is needed
Maybe avoid a split in the middle of a sentence ?

2024-08-01 18:19 UTC, ericvergnaud approved these changes

2024-08-02 11:07 UTC, nfx approved these changes

2024-08-02 11:07 UTC, merged