Refactor view sequencing and return sequenced views if recursion is found
databrickslabs/ucx pull request #2499
Opened 2024-08-28 11:30 UTC by JCZuurmond

## Changes
Refactor view sequencing and return sequenced views if recursion is found

### Linked issues
Resolves #2494

### Functionality

- [ ] added a new workflow
- [ ] modified existing workflow: `table-migration`

### Tests

- [ ] updated unit tests

2024-08-28 11:33 UTC, JCZuurmond reviewed
Did the refactor to improve code readability and to look for the possible origin of the problem

2024-08-28 13:06 UTC, JCZuurmond commented
CI failure is unrelated. Fixed in https://github.com/databrickslabs/ucx/pull/2500

2024-08-28 17:33 UTC, ericvergnaud requested changes

2024-08-29 21:05 UTC, nfx approved these changes
lgtm

2024-08-29 21:05 UTC, nfx commented on src/databricks/labs/ucx/hive_metastore/view_migrate.py
> +            raise RecursionError(f"Unresolved dependencies prevent batch sequencing: {views}")
ideally we'd not rely on exceptions for control flow, but let's continue with this one

2024-08-29 21:05 UTC, merged