Fixes pip install statement in debug notebook
databrickslabs/ucx pull request #2545
Opened 2024-09-05 21:41 UTC by pritishpai

## Changes
pip install wheel is surrounded by [ ] which fails the notebook run. 

### Linked issues
Quick fix

### Functionality
- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests
- [x] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-09-05 21:42 UTC, pritishpai commented
Before:
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/11e6bab8-2c33-4b85-8bae-0f82bbf79572">

2024-09-05 21:44 UTC, pritishpai commented
Fixed
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/250c47b6-4ff1-44fa-98a9-9cec711dca9e">

2024-09-06 08:51 UTC, ericvergnaud approved these changes
lgtm

2024-09-06 14:19 UTC, nfx commented
@pritishpai make sure integration tests passes

2024-09-06 14:20 UTC, nfx requested changes
@pritishpai make sure integration tests passes

2024-09-09 20:35 UTC, pritishpai commented
Failing integration test test_running_real_remove_backup_groups_job to be resolved when https://github.com/databrickslabs/ucx/pull/2557 is merged.

2024-09-10 08:56 UTC, JCZuurmond reviewed
@pritishpai : Could you add a test showing that this now works where it did not before? The code changes LGTM

2024-09-10 14:16 UTC, pritishpai commented
> @pritishpai : Could you add a test showing that this now works where it did not before? The code changes LGTM

@JCZuurmond I have added the screenshot of manual testing (fails when its surrounded by sq brackets and passes without it)

2024-09-10 15:03 UTC, merged