Adding comment on the source tables to capture that they have been deprecated
databrickslabs/ucx pull request #2548
Opened 2024-09-06 06:41 UTC by aminmovahed-db

Solves #2375

## Changes

### Linked issues

Resolves #..

### Functionality

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-09-06 06:43 UTC, aminmovahed-db commented
These are the screenshots of this feature...
![image](https://github.com/user-attachments/assets/84e51d84-f6bb-40c5-ac60-9270c19961c0)

![image](https://github.com/user-attachments/assets/e6825e09-f42d-4533-ad4e-43e6eaa02641)

2024-09-06 07:28 UTC, asnare reviewed
From a design perspective: Should this modify any existing comment on the table (by prepending?), rather than just overwriting it?

I'd really like to see an integration test.

2024-09-06 14:25 UTC, nfx approved these changes
lgtm

2024-09-09 07:14 UTC, JCZuurmond requested changes
One minor detail

2024-09-09 07:14 UTC, JCZuurmond commented on src/databricks/labs/ucx/hive_metastore/table_migrate.py
> +    def _sql_add_comment(self, table: Table, target_table_key: str):
Make it more explicit which comment is added

```suggestion
    def _sql_add_deprecated_comment(self, table: Table, target_table_key: str):
        """Docs: https://docs.databricks.com/en/data-governance/unity-catalog/migrate.html#add-comments-to-indicate-that-a-hive-table-has-been-migrated"""
    
```

2024-09-10 08:03 UTC, JCZuurmond approved these changes
one comment, otherwise lgtm

2024-09-10 08:03 UTC, JCZuurmond commented on src/databricks/labs/ucx/hive_metastore/table_migrate.py
> +    def _sql_add_deprecated_comment(self, table: Table, target_table_key: str):
Sorry, rereading the link in the docs. The following is probably better:

```suggestion
    def _sql_add_migrated_comment(self, table: Table, target_table_key: str):
```

2024-09-10 08:05 UTC, JCZuurmond requested changes
Comment on view does not work

2024-09-11 17:13 UTC, merged