Adds ability for crawlers to write to other catalogs than hive_metastore
databrickslabs/ucx pull request #2636
Opened 2024-09-13 17:24 UTC by pritishpai

## Changes
Currently, all crawlers write to the inventory database under the hard-coded "hive_metastore". This will allow the users to use a custom catalog for writing ucx metadata.

### Linked issues
Introduces #2575 

### Functionality

- [ ] added relevant user documentation
- [ ] added new CLI command
- [ ] modified existing command: `databricks labs ucx ...`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [ ] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-09-17 13:45 UTC, JCZuurmond reviewed
Looking good, added some comments. Make sure you got all the `hive_metastore` references

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/account/aggregate.py
> +                # TODO: check whether to add catalog here as well
I expect not

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/contexts/application.py
> +            self.workspace_client, self.sql_backend, self.inventory_catalog, self.inventory_database
```suggestion
            self.workspace_client, self.sql_backend, self.inventory_catalog, self.inventory_database,
```

and format

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/contexts/workflow_task.py
> +        return JobsCrawler(self.workspace_client, self.sql_backend, self.inventory_catalog, self.inventory_database)
```suggestion
        return JobsCrawler(self.workspace_client, self.sql_backend, self.inventory_catalog, self.inventory_database, )
```

and format

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/hive_metastore/locations.py
> +    def __init__(self, backend: SqlBackend, ws: WorkspaceClient, inventory_catalog: str, inventory_database: str):
Note that it is called `inventory_catalog` and `inventory_database` here where the others have just `catalog` and `schema`, maybe clean that up

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/install.py
> +        inventory_catalog = self.prompts.question("Inventory Catalog", default=default_catalog, valid_regex=r"^\w+$")
I do not think we want to do this. We still want the inventory to be in the `hive_metastore` (always), but need the drop in for the catalog to built the history table #2572

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/mixins/fixtures.py
> +def inventory_catalog():
Is this needed? A test could just use `make_catalog` right?

2024-09-17 13:45 UTC, JCZuurmond commented on src/databricks/labs/ucx/workspace_access/manager.py
> +        self, backend: SqlBackend, inventory_catalog: str, inventory_database: str, crawlers: list[AclSupport]
```suggestion
        self, backend: SqlBackend, inventory_catalog: str, inventory_database: str, crawlers: list[AclSupport],
```

2024-09-17 13:45 UTC, JCZuurmond commented on tests/integration/aws/test_access.py
> +# TODO remove the disables and use ctx fixtures
👍

2024-09-17 13:45 UTC, JCZuurmond commented on tests/integration/aws/test_credentials.py
> +        location = ExternalLocations(ws, sql_backend, "hive_metastore", "inventory_schema")
Not part of your changes: but would expect a dynamic schema or catalog here too

2024-09-18 13:17 UTC, nfx requested changes
to align with @asnare

2024-09-18 13:17 UTC, nfx commented on src/databricks/labs/ucx/account/aggregate.py
> +                            dst_catalog=ctx.config.inventory_catalog,
revert, catalog will always be the same for this one. let's defer it to the time when we actually have our catalog.

2024-09-18 13:17 UTC, nfx commented on src/databricks/labs/ucx/account/aggregate.py
> +                # TODO: check whether to add catalog here as well
+1

2024-09-18 13:17 UTC, nfx commented on src/databricks/labs/ucx/config.py
> +    inventory_catalog: str = "hive_metastore"
revert this change. we'll always have data in HMS (when we run run on existing workspaces)

2024-09-19 08:25 UTC, closed without merging