Whitelists cmdstanpy
databrickslabs/ucx pull request #2786
Opened 2024-10-02 15:38 UTC by pritishpai

## Changes
Whitelists cmdstanpy

### Linked issues
Partly resolve #1931

2024-10-02 17:46 UTC, nfx requested changes

2024-10-02 17:46 UTC, nfx commented on src/databricks/labs/ucx/source_code/known.json
> +        "code": "direct-filesystem-access",
these are false positives - pystan doesn't access cloud storage

2024-10-02 18:09 UTC, pritishpai commented on src/databricks/labs/ucx/source_code/known.json
> +        "code": "direct-filesystem-access",
Removed direct file system references

2024-10-03 15:03 UTC, nfx approved these changes
lgtm

2024-10-03 15:03 UTC, merged