Whitelists dm-tree
databrickslabs/ucx pull request #2789
Opened 2024-10-02 16:00 UTC by pritishpai

## Changes
Whitelists dm-tree

### Linked issues
Partly resolve #1931

2024-10-02 17:49 UTC, nfx requested changes

2024-10-02 17:49 UTC, nfx commented on src/databricks/labs/ucx/source_code/known.json
> +        "message": "The use of direct filesystem references is deprecated: /"
are you sure it's using spark?

2024-10-03 14:37 UTC, pritishpai commented on src/databricks/labs/ucx/source_code/known.json
> +        "message": "The use of direct filesystem references is deprecated: /"
not using spark. removing.

2024-10-03 15:04 UTC, nfx approved these changes
lgtm

2024-10-03 15:05 UTC, merged