Added used tables in assessment dashboard
databrickslabs/ucx pull request #2836
Opened 2024-10-04 12:38 UTC by ericvergnaud

## Changes
Adds a widget in the assessment dashboard for displaying used tables

### Linked issues
None

### Functionality
- [x] added some UI

### Tests
- [x] verified on staging environment:

https://github.com/user-attachments/assets/64de0164-26dd-4470-b51d-b564266c8604

2024-10-04 12:44 UTC, ericvergnaud commented on src/databricks/labs/ucx/queries/assessment/main/36_0_direct_filesystem_access_problems.md
> +- Points to a direct filesystem access detected in the code using the code path, query or workflow & task reference;
Fix typo, not worth a dedicated PR

2024-10-04 15:15 UTC, nfx requested changes
produced records are incorrect - what's displayed on a demo is DFSA, e.g. 

```
format.`/path/to/file`
```

where `format` is usually `delta`, `parquet`, `csv`, `json`, `text`, `binaryFiles`, and some more things.

![image](https://github.com/user-attachments/assets/8ab84d5c-10fe-4e9b-b68a-a8b32415c8d0)

2024-10-04 15:15 UTC, nfx commented on src/databricks/labs/ucx/source_code/queries.py
> +            yield UsedTable(**asdict(table)).replace_source(
```suggestion
            yield UsedTable(**asdict(table)).replace_source(
```
use dataclasses.replace instead

2024-10-04 16:23 UTC, ericvergnaud commented
> produced records are incorrect - what's displayed on a demo is DFSA, e.g.
> 
> ```
> format.`/path/to/file`
> ```
> 
> where `format` is usually `delta`, `parquet`, `csv`, `json`, `text`, `binaryFiles`, and some more things.
> 
> ![image](https://private-user-images.githubusercontent.com/259697/373694333-8ab84d5c-10fe-4e9b-b68a-a8b32415c8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTkyMTIsIm5iZiI6MTcyODA1ODkxMiwicGF0aCI6Ii8yNTk2OTcvMzczNjk0MzMzLThhYjg0ZDVjLTEwZmUtNGU5Yi1iNjhhLWE4YjMyNDE1YzhkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjIxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjNjMWY5Y2Q1NzZiZjJhZDgzN2JmYzdjZmM4ZmJkZTc3M2Q5ZDc1NzYwNmJlZWQ1ZWJmMjllZmFiZTg5MzRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._ApKh3PWSNnWLJL3ZZ4hjv6aqxFqjk2l4m6L2xdtx1w)

Fixed by https://github.com/databrickslabs/ucx/pull/2841

2024-10-04 16:26 UTC, ericvergnaud commented on src/databricks/labs/ucx/source_code/queries.py
> +            yield UsedTable(**asdict(table)).replace_source(
simplified - replace_source uses dataclesses.replace

2024-10-09 09:59 UTC, nfx approved these changes
lgtm

2024-10-09 09:59 UTC, merged