Avoid resource conflicts in integration tests by using a random dir name
databrickslabs/ucx pull request #2865
Opened 2024-10-08 12:45 UTC by ericvergnaud

## Changes
Replace hard-coded dir name with random one

### Linked issues
Resolves #2797 

### Functionality
None

### Tests
- [x] ran integration tests

2024-10-08 13:17 UTC, nfx approved these changes
lgtm

2024-10-08 18:57 UTC, nfx requested changes

2024-10-09 09:32 UTC, ericvergnaud commented on tests/integration/hive_metastore/test_migrate.py
>      # TODO: Remove this hack below
done

2024-10-09 09:51 UTC, nfx approved these changes
lgtm

2024-10-09 10:20 UTC, merged