improve type hints
databrickslabs/ucx pull request #2966
Opened 2024-10-15 12:11 UTC by ericvergnaud

## Changes
Add type hints

### Linked issues
None

### Functionality
None

### Tests
- [x] ran unit tests

2024-10-15 12:48 UTC, nfx requested changes

2024-10-15 12:48 UTC, nfx commented on src/databricks/labs/ucx/assessment/azure.py
> +        all_clusters_by_id = {c.cluster_id or "": c for c in self._ws.clusters.list()}
skip the cluster

2024-10-15 12:48 UTC, nfx commented on src/databricks/labs/ucx/assessment/jobs.py
> +        all_clusters = {c.cluster_id or "": c for c in self._ws.clusters.list()}
skip the cluster

2024-10-16 09:39 UTC, ericvergnaud commented on src/databricks/labs/ucx/assessment/azure.py
> +        all_clusters_by_id = {c.cluster_id or "": c for c in self._ws.clusters.list()}
done

2024-10-16 12:16 UTC, nfx approved these changes
lgtm

2024-10-16 12:16 UTC, merged