Removed Job Clusters from Clusters Crawler
databrickslabs/ucx pull request #298
Opened 2023-09-25 18:34 UTC by FastLee

Closed #279

2023-09-25 20:40 UTC, nfx requested changes

2023-09-25 20:40 UTC, nfx commented on src/databricks/labs/ucx/assessment/crawlers.py
> +            if cluster.cluster_source != ClusterSource.JOB:
Diff is too big, do "if cluster source is job, continue". It's more readable that way as well

2023-09-26 07:25 UTC, larsgeorge-db approved these changes
Please apply the feedback form Serge.

2023-09-26 13:48 UTC, nfx approved these changes

2023-09-26 13:49 UTC, merged