Added `mosaicml-streaming` to known list
databrickslabs/ucx pull request #3029
Opened 2024-10-21 13:28 UTC by pritishpai

## Changes
Added `mosaicml-streaming` to known list 

### Linked issues
Partly resolve #1931

2024-10-22 09:26 UTC, nfx requested changes
reduce the size of the diff to <20 lines

2024-10-23 15:54 UTC, pritishpai commented on src/databricks/labs/ucx/source_code/known.json
> +    "torchvision.datasets": [],
Had to keep torchvision.datasets as one of the libraries has to be excluded, so just included all but torchvision.datasets.widerface
`    "torchvision.datasets.widerface": [
      {
        "code": "direct-filesystem-access",
        "message": "The use of direct filesystem references is deprecated: /"
      }
    ],`

2024-10-24 10:38 UTC, nfx approved these changes
lgtm

2024-10-29 13:33 UTC, nfx approved these changes
lgtm

2024-10-29 13:33 UTC, merged