Fix Integration test failure of migration_tables
databrickslabs/ucx pull request #3108
Opened 2024-10-31 09:13 UTC by HariGS-DB

## Changes

Resolves #3054 and #3055

### Functionality

### Tests

- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-10-31 11:58 UTC, JCZuurmond requested changes
@HariGS-DB : How are the issues resolved?

2024-10-31 21:26 UTC, nfx approved these changes
lgtm

2024-11-01 08:34 UTC, JCZuurmond approved these changes

2024-11-01 16:25 UTC, nfx approved these changes
lgtm

2024-11-01 16:25 UTC, merged