Adds existing fixtures to context and change usages accordingly
databrickslabs/ucx pull request #3437
Opened 2024-12-11 18:27 UTC by pritishpai

## Changes
Add fixtures to context and change usages accordingly

### Linked issues
Resolves #3428 

### Functionality
- [x] refactored tests

### Tests
- [x] use existing integration tests

2024-12-11 20:03 UTC, pritishpai commented
The pylint disable is unavoidable here as we are adding more fixtures to the context.

2024-12-12 08:20 UTC, JCZuurmond requested changes
Changes LGTM; have another request

2024-12-12 08:20 UTC, JCZuurmond commented on tests/integration/workspace_access/test_workflows.py
>      # TODO: Move `include_object_permissions` to context like other `include_` attributes
Could you make sure this is happening too? Similar to how the `make_schema` adds the created schema to the database.

2024-12-12 08:21 UTC, JCZuurmond commented
> The pylint disable is unavoidable here as we are adding more fixtures to the context.

@gueniai  can bypass the CI to circumvent the "no-cheat" one. (After we reviewed and approved the code.)

2024-12-16 08:28 UTC, JCZuurmond reviewed
see comments

2024-12-16 08:28 UTC, JCZuurmond commented on tests/integration/conftest.py
> +            self.config.include_object_permissions = []
Please create a new attribute for the `include_object_permissions` and added to the config like `include_databases` and `created_databases`

2024-12-16 08:28 UTC, JCZuurmond commented on tests/integration/conftest.py
> +    def configure_include_object_permissions(self) -> None:
```suggestion
    @property
    def created_object_permissions(self) -> list[str]:
```

2024-12-20 14:53 UTC, JCZuurmond approved these changes
LGTM, before merging make sure to run the full integration test suite for your branch as these changes effect many tests:

1. Go to https://github.com/databrickslabs/ucx/actions/workflows/nightly.yml
2. Use the "Run workflow" drop down
3. Select your branch
4. Run the CI

2024-12-20 18:44 UTC, pritishpai commented
Nightly passed on 2nd attempt https://github.com/databrickslabs/ucx/actions/runs/12435607581

> > The pylint disable is unavoidable here as we are adding more fixtures to the context.
> 
> @gueniai can bypass the CI to circumvent the "no-cheat" one. (After we reviewed and approved the code.)

@gueniai need your approval to bypass the "no-check" check

2025-01-06 17:56 UTC, merged