Implement disposition field in SQL backend
databrickslabs/ucx pull request #3448
Opened 2024-12-13 16:48 UTC by micheledaddetta-databricks

This feature aims to the chance of running SQL statement for assessment results export in case of large workspaces with a large amount of findings.  
Introducing the `query_statement_disposition` value during the UCX installation can allow users to select the proper disposition method to use when running large queries. This parameter is added in the `config.yml` file and used for the SqlBackend definition. Using this approach, large queries will not fail.

## Changes
Added SQL query statement disposition choice during the UCX installation
Added `query_statement_disposition` value in the config file

### Linked issues

Resolves [#3447](https://github.com/databrickslabs/ucx/issues/3447)

### Functionality

- [ ] added relevant user documentation
- [ ] added new CLI command
- [X] modified existing commands: `databricks labs install ucx`, `databricks labs ucx export-assessment`
- [ ] added a new workflow
- [ ] modified existing workflow: `...`
- [ ] added a new table
- [ ] modified existing table: `...`

### Tests

- [X] manually tested
- [ ] added unit tests
- [ ] added integration tests
- [ ] verified on staging environment (screenshot attached)

2024-12-13 16:58 UTC, JCZuurmond requested changes
@micheledaddetta-databricks : Thanks for the contribution. We need @gueniai to confirm your Github handle has the CLA signed. Can you make sure your git commits signature is verified (https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)?

2024-12-16 07:49 UTC, micheledaddetta-databricks commented on src/databricks/labs/ucx/source_code/known.json
>      "audioread.rawread": [],
Done

2024-12-16 08:22 UTC, JCZuurmond commented on src/databricks/labs/ucx/install.py
> +            "Do you want to use the EXTERNAL_LINKS disposition value for query statements? (Only needed with large workspaces)"
```suggestion
            "Do you want to use the `EXTERNAL_LINKS` disposition for query statements? (Only needed when exporting more than 25 MiB of data from workspaces with many resources)"
```

2024-12-16 10:51 UTC, micheledaddetta-databricks commented
Hello @JCZuurmond thanks for taking in charge the request! I just set up my git commits signature. Is that an issue for previous commits?

2024-12-16 12:23 UTC, JCZuurmond commented
> Hello @JCZuurmond thanks for taking in charge the request! I just set up my git commits signature. Is that an issue for previous commits?

I cannot tell, @gueniai can maybe figure this out for us

2024-12-19 04:26 UTC, gueniai commented
Hi @micheledaddetta-databricks , thank you for the PR and for verifying the signature. Unfortunately the previous commits are not automatically also verified. You can try with an interactive rebase, but I have a feeling you're going to need to re-create the PR :/

2024-12-19 10:11 UTC, closed without merging