Crawler for Externally Orchestrated Jobs with Failing Configuration
databrickslabs/ucx pull request #395
Opened 2023-10-06 16:40 UTC by zpappa

Resolves #266

**Added ExternallyOrchestratedJobsWithFailingConfigCrawler**
Added a crawler to look at JobRuns from the SDK and determine which of the job runs are from the RunsSubmit API

**Added Unit Tests**
Added tests to cover basic logic and some edge cases

**Integration Tests Pending**

2023-10-06 17:08 UTC, nfx requested changes
needs a passing integration test. please attach a screenshot once you get it to work locally

2023-10-09 13:40 UTC, FastLee requested changes

2023-10-09 13:40 UTC, FastLee commented on src/databricks/labs/ucx/assessment/crawlers.py
> +@dataclass
Do we want to capture only the failing ones or all of them with the failing one anotated?

2023-10-09 13:40 UTC, FastLee commented on src/databricks/labs/ucx/assessment/crawlers.py
> +    """
Does it require implementation?

2023-10-09 13:40 UTC, FastLee commented on src/databricks/labs/ucx/assessment/crawlers.py
> +    left = (int(lvg.group("major")), int(lvg.group("minor")))
Do we have a proper unit test for that?

2023-10-09 13:40 UTC, FastLee commented on src/databricks/labs/ucx/assessment/crawlers.py
> +    task: RunTask, job_run: BaseRun, all_clusters: dict[str, ClusterDetails]
Re factor job cluster to use the same mechanism

2023-10-09 13:40 UTC, FastLee commented on src/databricks/labs/ucx/assessment/crawlers.py
> +        no_of_days_back = datetime.timedelta(days=30)  # todo make configurable in yaml?
Make timedelta externally configurable

2024-01-30 09:11 UTC, closed without merging