make the group migration restartable
databrickslabs/ucx pull request #423
Opened 2023-10-10 10:58 UTC by mwojtyczka

Fix for issue 386

2023-10-10 11:16 UTC, nfx requested changes
see comments. also i'd require an integration test for this, otherwise we're not sure this fix actually works.

2023-10-10 11:16 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/groups.py
> +
remove blank line here

2023-10-10 11:16 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/groups.py
> +
remove blank line here

2023-10-10 11:16 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/groups.py
> -        self._workspace_groups.append(backup_group)
revert this removal

2023-10-10 11:16 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/groups.py
> -            return True
revert this removal

2023-10-10 11:16 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/groups.py
> -            logger.info("No groups were loaded or initialized, nothing to do")
revert this removal

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert manager.migration_groups_provider.groups == [group_info]
don't change the existing tests

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert compare(manager.migration_groups_provider.groups, [ds_group_info, de_group_info])
don't change the existing tests

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert manager.migration_groups_provider.groups == [group_info]
don't change the existing tests

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert manager.migration_groups_provider.groups == [group_info]
don't change the existing tests

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert len(manager.migration_groups_provider.groups) == 0
don't change the existing tests

2023-10-10 11:16 UTC, nfx commented on tests/unit/workspace_access/test_groups.py
> +    assert len(manager.migration_groups_provider.groups) == 0
don't change the existing tests

2023-10-10 11:51 UTC, mwojtyczka commented
> see comments. also i'd require an integration test for this, otherwise we're not sure this fix actually works.

I agree, I will add integration tests.

2023-10-12 08:58 UTC, closed without merging

2023-10-12 08:59 UTC, mwojtyczka commented
won't do, as the functionality is already covered with different PR