fix the entitlements application for account-level groups
databrickslabs/ucx pull request #529
Opened 2023-10-30 19:09 UTC by renardeinside

Addresses the issues in #488 .

**Problem Statement**

TODO

**Design**

TODO

2023-11-02 08:37 UTC, william-conti requested changes

2023-11-02 08:37 UTC, william-conti commented on tests/integration/workspace_access/test_scim.py
> +    pi.apply_group_permissions(group_manager.migration_state, destination="account")
Migration state must be re-instatiated between each invocations, the same as we do in runtime.py.

The test should look like this then:

```
def test_scim(ws: WorkspaceClient, make_ucx_group, sql_backend, inventory_schema):
    """
    This test does the following:
    * create a ws group with roles and entitlements
    * migrate this group
    * verify that the migrated group has the same roles and entitlements
    :return:
    """
    ws_group, acc_group = make_ucx_group()

    _patch_by_id(ws, ws_group.id, "entitlements", [iam.ComplexValue(value="databricks-sql-access")])
    groups_config = GroupsConfig(selected=[ws_group.display_name])

    #Task 1 - crawl_permissions
    scim_support = ScimSupport(ws)
    pi = PermissionManager(sql_backend, inventory_schema, [scim_support])
    pi.cleanup()
    pi.inventorize_permissions()

    # Task 2 - apply_permissions_to_backup_groups
    group_manager = GroupManager(ws, groups_config)
    group_manager.prepare_groups_in_environment()
    pi.apply_group_permissions(group_manager.migration_state, destination="backup")

    #Task 3 - apply_permissions_to_account_groups
    group_manager = GroupManager(ws, groups_config)
    group_manager.prepare_groups_in_environment()
    group_manager.replace_workspace_groups_with_account_groups()

    #Task 4 - apply_permissions_to_account_groups
    migration_state = GroupManager.prepare_apply_permissions_to_account_groups(ws, groups_config.backup_group_prefix)
    pi.apply_group_permissions(migration_state, destination="account")
    assert iam.ComplexValue(value="databricks-sql-access") in ws.groups.get(acc_group.id).entitlements
```

Which, in my environment, doesn't pass

2023-11-02 09:15 UTC, nfx commented
Keep in mind that we're getting rid of the backup groups very soon: https://github.com/databrickslabs/ucx/pull/450/files

2023-11-02 10:14 UTC, renardeinside commented
@nfx could you please tell us what "very soon" means specifically? is it in 2-3 days or we're speaking about longer time periods I would suggest going further with proper fix.

2023-11-02 20:23 UTC, nfx reviewed
Changes are probably fine, but all integration tests must pass for this to merge. 

Keep in mind that #450 is doing the fix fundamentally.

2023-11-03 12:00 UTC, renardeinside reviewed
would be nice to address the backend topic (I have a feeling it's errorneous).

2023-11-03 12:55 UTC, william-conti commented on src/databricks/labs/ucx/runtime.py
> +    remote_state = GroupMigrationState().fetch_migration_state(RuntimeBackend(), cfg.inventory_database)
Fixed

2023-11-03 13:57 UTC, william-conti approved these changes

2023-11-03 15:38 UTC, merged