Bug: Update tables.scala to read inventory database from config.yml file
databrickslabs/ucx pull request #614
Opened 2023-11-21 23:40 UTC by HariGS-DB

Description: tables.scala code is retrieving inventory_database from a separate widget called inventory_database. While other tasks are reading inventory_database from the config.yml. It results in a scenario where user updates the existing config.yml and all tasks start referring to the new inventory_database but tables.scala still refers to the original widget inventory_database.
Solution:
Made code changes to read the config.yaml widget and load the content of the yaml and retrieve the inventory_database from the config file. The tables and table_errors are created in the inventory_database referred in the config.yml file.
This makes it consistent.

2023-11-22 10:45 UTC, nfx reviewed
I'm fine with merging this after tiny refactoring and passing integration tests.

2023-11-22 10:45 UTC, nfx commented on src/databricks/labs/ucx/hive_metastore/tables.scala
> +val inventoryDatabase = obj.get("inventory_database")
can you refactor this into a single function, that returns just `inventoryDatabase`, so that we don't pollute global namespace

2023-11-22 15:22 UTC, nfx requested changes

2023-11-22 15:22 UTC, nfx commented on CONTRIBUTING.md
> +With the final results looking like (Note, for Azure Cloud, no `DATABRICKS_TOKEN` value):
please rebase, this is a change from the other commit

2023-11-22 15:22 UTC, nfx commented on src/databricks/labs/ucx/hive_metastore/tables.scala
> +  dbutils.widgets.text("config", "/Workspace/Users/hari.selvarajan@databricks.com/.ucx/config.yml")
```suggestion
  dbutils.widgets.text("config", "")
```
don't hardcode your username, add a check for config not being empty

2023-11-22 20:04 UTC, HariGS-DB commented
<img width="1479" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/a72586df-8d7c-47fe-8524-1872be1665b3">

2023-11-22 20:04 UTC, HariGS-DB commented
local integration passed for test_jobs_with_no_inventory_database

2023-11-23 11:05 UTC, HariGS-DB commented
<img width="1148" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/c63a1d72-f807-483a-9d48-3ae77c684cb9">

2023-11-23 23:40 UTC, HariGS-DB commented
<img width="1562" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/25420796-fb53-4419-a406-dc3c2c0a38bc">
Completed all integration test locally

2023-11-24 16:48 UTC, william-conti approved these changes
LGTM, always the same tests that doesn't pass ...

2023-11-24 20:41 UTC, merged