Added filters to run only cloud specific task
databrickslabs/ucx pull request #681
Opened 2023-12-07 05:24 UTC by prajin-29

may close #460

2023-12-07 05:50 UTC, nfx requested changes

2023-12-07 05:50 UTC, nfx commented on src/databricks/labs/ucx/framework/tasks.py
> +    is_gcp: bool = False
use only one `cloud: str` field

2023-12-08 12:11 UTC, prajin-29 commented on src/databricks/labs/ucx/framework/tasks.py
> +    is_gcp: bool = False
updated this part to cloud:str

2023-12-13 17:22 UTC, nfx approved these changes

2023-12-13 17:23 UTC, merged