Parallising model listing to speed up inventory
databrickslabs/ucx pull request #691
Opened 2023-12-13 23:33 UTC by HariGS-DB

Change description:
This PR makes changes to the model listing process. Currently the model listing is done serially which takes time in workspace with large number of registered models. This changes uses python threads to parallelize model listing to speed up the inventory process for models
Changes details:
Updates to generic.py.model_listing() to use ThreadPoolExecutor to parallise get_model function
It accepts num_threads from config.
Also updated the relevant test cases

2023-12-13 23:46 UTC, HariGS-DB commented
Screenshot of test_workspace_access.test_workspace_acces_e2e.
Before the change, time taken for model listing
<img width="811" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/05920ccd-add0-4aec-8c09-89a19d290ee1">
After change, time take for model listing
<img width="854" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/2b71e4ce-021f-4ac6-8886-21d148af71bd">

2023-12-14 00:09 UTC, nfx requested changes

2023-12-14 00:09 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/generic.py
> +        with ThreadPoolExecutor(num_threads) as pool:
use `Threads.gather`, it's a tested way, which properly recovers from errors.

2023-12-14 00:58 UTC, HariGS-DB commented
Changes done.
Updated screenshot of model listing
<img width="980" alt="image" src="https://github.com/databrickslabs/ucx/assets/105197202/62d7fd11-4914-425b-b857-532a9d323929">

2023-12-14 01:02 UTC, nfx requested changes

2023-12-14 01:02 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/generic.py
> +        models, errors = Threads.gather("listing model ids", tasks, num_threads)
and what do you do with errors? `/dev/null`? what if something fails?

throw ManyErrors.

https://github.com/databrickslabs/ucx/blob/main/src/databricks/labs/ucx/framework/parallel.py#L18-L22

2023-12-14 01:11 UTC, nfx requested changes

2023-12-14 01:11 UTC, nfx commented on src/databricks/labs/ucx/workspace_access/generic.py
> +            logger.error(f"Detected {len(errors)} errors while listing models")
throw errors, don't log. nobody reads the logs.

2023-12-14 01:31 UTC, merged