Reorganize assessment dashboard to increase readability
databrickslabs/ucx pull request #738
Opened 2023-12-23 22:57 UTC by dmoore247

Closes #734

2023-12-24 11:05 UTC, nfx requested changes
Please fix the conflict and provide a screenshot of the change as part of the PR description

2023-12-24 11:05 UTC, nfx commented on src/databricks/labs/ucx/queries/assessment/main/01_2_assessment_summary.sql
> +<<<<<<< HEAD:src/databricks/labs/ucx/queries/assessment/main/01_2_assessment_summary.sql
Bug: Unresolved git conflict.

2024-01-02 14:33 UTC, dmoore247 commented on src/databricks/labs/ucx/queries/assessment/main/01_2_assessment_summary.sql
> +<<<<<<< HEAD:src/databricks/labs/ucx/queries/assessment/main/01_2_assessment_summary.sql
fixed

2024-01-03 15:59 UTC, nfx approved these changes

2024-01-03 16:00 UTC, merged